### ISSUE TITLE
add "Type:" to code.json

### ISSUE THREAD

**Issue by troddick** [USGS-WiM/wimrepo-dashboard#2]
- [x] add a "Type" to code.json that will give the repo owner a choice to choose from (similar to status) 
`["application", "service"]`

- [x] add the type chosen to the repos response in the app.component.ts file where other code.json properties are brought up (line 33-49)

- [x] add the header to `this.displayedColumnsWith` and also to the app.component.html table

**Comment by HansVraga** [comment]
We need to review the code.json schema to see how best to add 'type'

**Comment by kjacobsen16** [comment]
Using "tags" for this.  Added examples to wimpo, filled in for a couple repos as examples.
