### ISSUE TITLE
Sort doesn't seem to work

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/wimrepo-dashboard#20]
I'm trying to sort by status, but after sort the status's aren't grouped:

![image](https://user-images.githubusercontent.com/12058013/55802104-86d94380-5aa5-11e9-8023-26ba479bd3ee.png)

**Comment by kjacobsen16** [comment]
issue is with how status is filled in:

![image](https://user-images.githubusercontent.com/35497731/55803045-2d6e1600-5a9f-11e9-904d-a4fe2554b6cc.png)
![image](https://user-images.githubusercontent.com/35497731/55803059-33fc8d80-5a9f-11e9-8452-27da7052c66f.png)
